# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d451842294eba77db17f3575fe3fb4d4b0107a0e6596d63edbafda34cf06b20fe96f4ba4c5fa6ddd22cda79764e13a063323f4df808cfe3f57dcda52c1484916

test:
  secret_key_base: 7ad3353cae75c214e875c7cbe9746f56e24c0bd450a1fca936161f4ca5bf33b3e703508e4e79809103b1414d7e5e28658ad16e4216961b6ad4100c8c80da3b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
